### PR TITLE
Merge pull request #6 from ICLDisco/master

### PR DESCRIPTION
**Pull request by eddy16112**
update to most recent disco ompi

### CODE REVIEW

**Comment by thananon** [comment]
Noooo, what did you do???/!?

**Comment by bosilca** [comment]
Don't pull it, I will alter the history asap.

**Comment by eddy16112** [comment]
There is a revert button on this page, but it will create another pull request to revert

**Comment by thananon** [comment]
what?! that sounds very bad. 😿

**Pull request merged**
