### PR TITLE
Export/errors waitsync

### PR DESCRIPTION
**Pull request by abouteiller**

### CODE REVIEW

**Comment by abouteiller** [comment]
After careful re-review, it appears that there is no (relevant) race condition.

In general terms, what happens here is that the sync object may be updated to a count of 0 when a failure is detected (even if none of the attached requests has an error). When that happens, we jump to recheck, rearm the sync, recount the number of reqs to complete, and redo the sync.

The race condition I suspected would be due to having the sync object attached to some request when we reset the sync target count for the second time after jumping to `recheck:`. It is indeed possible that we compute the wrong target for the sync value (i.e., some of the requests have already completed, or complete while we are counting the second time). However, every time that happens, we recount the number of already completed requests, and act accordingly (either by re-adjusting the sync target with an update, or jumping directly to completion). Thus it appears that this race condition is 1) pre-existing due to the fact that the sync may complete requests while we are still counting num_active/completed even during the first round and 2) already managed correctly.

@thananon please confirm that there's no issue here.

**Comment by thananon** [comment]
I see `wait_all` might deadlock here if a request is completed during we are kicking everyone out of `sync_wait` because we are rearm the sync with the original count. With a single request already completed, the sync will never be released.

**Comment by abouteiller** [comment]
I don't think so, because we will then recount `completed`, and then issue a `wait_sync_update(completed)`.

**Comment by abouteiller** [comment]
This PR is outdated. A newer version of the wakeup logic is in pr #41

**Pull request closed without merging**
